# Generated by Django 5.1.1 on 2024-09-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('mobile', models.CharField(default='0000000000', max_length=15)),
                ('message', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='students',
            name='fullname',
        ),
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.EmailField(default='user@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='students',
            name='mobile',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='students',
            name='password',
            field=models.CharField(default='password123', max_length=50),
        ),
    ]
