# Generated by Django 5.1.1 on 2024-09-24 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_contact_delete_contacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contacts',
        ),
    ]
