# Generated by Django 5.1.1 on 2024-10-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_question_quiz_answer_question_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('expertise', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
