# Generated by Django 5.1.1 on 2024-10-06 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
