# Generated by Django 5.1.1 on 2024-10-06 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_content_delete_coursecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('quiz', 'Quiz'), ('project', 'Project')], max_length=50)),
                ('content_url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='myapp.courses')),
            ],
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
