# Generated by Django 5.1.1 on 2024-10-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_coursecontent_delete_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='content_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
