# Generated by Django 5.1 on 2024-10-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_coursecontent_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('point', models.IntegerField(default=0)),
                ('is_completed', models.CharField(default='Continue', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Projectsubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('number', models.IntegerField(default=0)),
            ],
        ),
    ]
