# Generated by Django 5.1 on 2024-10-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_enrollment_projectsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='is_completed',
            field=models.CharField(default='continue', max_length=255),
        ),
    ]
