# Generated by Django 5.1 on 2024-10-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_projectsubmission_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsubmission',
            name='code',
            field=models.TextField(default='Your code goes here..', max_length=10000),
        ),
    ]
